---
- name: innodb-replicaset-mysqlrouter-exporter | Check if mysqlrouter_exporter already installed
  stat: path=/usr/local/bin/mysqlrouter_exporter
  register: mysqlrouter_exporter_bin

- name: innodb-replicaset-mysqlrouter-exporter | Begin install mysqlrouter_exporter
  block:
    - name: innodb-replicaset-mysqlrouter-exporter | Download mysqlrouter_exporter release
      get_url:
        url: '{{ mysqlrouter_exporter_packages.url }}'
        dest: /usr/local/src/
        checksum: '{{ mysqlrouter_exporter_packages.checksum }}'
      register: mysqlrouter_exporter_src

    - name: innodb-replicaset-mysqlrouter-exporter | Extract  mysqlrouter_exporter_*.tar.gz
      unarchive:
        src: '{{ mysqlrouter_exporter_src.dest }}'
        remote_src: yes
        dest: /usr/local/bin/
        mode: 0755
        owner: root
        group: root
    
    - name: innodb-replicaset-mysqlrouter-exporter | Remove junk files
      file:
        path: /usr/local/bin/{{ item }}
        state: absent
      with_items:
        - LICENSE
        - NOTICE
        - README.md

  when: mysqlrouter_exporter_bin.stat.exists == False

- name: innodb-replicaset-mysqlrouter-exporter | Create mysqlrouter-exporter systemd service
  template:
    src: systemd/mysqlrouter-exporter.service.j2
    dest: /usr/lib/systemd/system/mysqlrouter-exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart mysqlrouter-exporter