---
scenario:
  innodb_cluster_and_mysqlrouter_on_the_same_instance:
    - lint
    - converge
    - verify
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: innodb-replicaset-0
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    privileged: true
    pre_build_image: true
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: innodb
    groups:
      - innodb-replicaset-infra
  - name: innodb-replicaset-1
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    privileged: true
    pre_build_image: true
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: innodb
    groups:
      - innodb-replicaset-infra
provisioner:
  name: ansible
  ansible_args:
    - --inventory=../../tests/inventory
    - --skip-tags=update-etc-hosts
  config_options:
    defaults:
      deprecation_warnings: false
      callback_whitelist: timer,profile_tasks
      fact_caching: jsonfile
      fact_caching_connection: ./cache
      forks: 100
    connection:
      pipelining: true
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}

verifier:
  name: ansible
